---
abstract: 'List of localities (cities/regencies) in Indonesia'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0.96
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-ID-Locality
requires:
  Perinci::CmdLine: 0
  Perinci::Sub::Gen::AccessTable: 0.11
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Locale-ID-Locality/
  repository: http://github.com/sharyanto/perl-Locale-ID-Locality
version: 0.03
